from typing import Any

class ndarray:
    T: "ndarray"
    def __matmul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> ndarray: ...
    def __add__(self, other: Any) -> ndarray: ...
    def __radd__(self, other: Any) -> ndarray: ...
    def __getitem__(self, key: Any) -> Any: ...

def array(object: Any, dtype: Any = ...) -> ndarray: ...
def diag(v: Any) -> ndarray: ...
def zeros(shape: Any, dtype: Any = ...) -> ndarray: ...
def asarray(a: Any, dtype: Any = ...) -> ndarray: ...
def cumprod(a: Any, axis: Any = ...) -> ndarray: ...

class random:
    @staticmethod
    def normal(
        loc: Any = ..., scale: Any = ..., size: Any = ...
    ) -> ndarray: ...
    @staticmethod
    def uniform(
        low: Any = ..., high: Any = ..., size: Any = ...
    ) -> ndarray: ...
