from typing import Any

class ndarray:
    T: "ndarray"
    ndim: int
    size: int
    shape: tuple[Any, ...]
    def __matmul__(self, other: Any) -> Any: ...
    def __neg__(self) -> ndarray: ...
    def __ge__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> ndarray: ...
    def __add__(self, other: Any) -> ndarray: ...
    def __radd__(self, other: Any) -> ndarray: ...
    def __sub__(self, other: Any) -> ndarray: ...
    def __rsub__(self, other: Any) -> ndarray: ...
    def __mul__(self, other: Any) -> ndarray: ...
    def __truediv__(self, other: Any) -> ndarray: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def min(self, axis: Any = ..., keepdims: Any = ...) -> Any: ...
    def max(self, axis: Any = ..., keepdims: Any = ...) -> Any: ...
    def mean(self, axis: Any = ..., keepdims: Any = ...) -> Any: ...
    def ravel(self) -> ndarray: ...

def array(object: Any, dtype: Any = ...) -> ndarray: ...
def diag(v: Any) -> ndarray: ...
def zeros(shape: Any, dtype: Any = ...) -> ndarray: ...
def ones(shape: Any, dtype: Any = ...) -> ndarray: ...
def full(shape: Any, fill_value: Any, dtype: Any = ...) -> ndarray: ...
def empty(shape: Any, dtype: Any = ...) -> ndarray: ...
def asarray(a: Any, dtype: Any = ...) -> ndarray: ...
def cumprod(a: Any, axis: Any = ...) -> ndarray: ...
def hstack(tup: Any) -> ndarray: ...
def sqrt(x: Any) -> ndarray: ...
def eye(N: Any, M: Any = ..., k: Any = ..., dtype: Any = ...) -> ndarray: ...
def log(x: Any) -> ndarray: ...
def clip(a: Any, a_min: Any = ..., a_max: Any = ...) -> ndarray: ...
def minimum(x1: Any, x2: Any) -> ndarray: ...
def quantile(a: Any, q: Any, axis: Any = ...) -> Any: ...
def median(a: Any, axis: Any = ...) -> Any: ...

class random:
    @staticmethod
    def normal(
        loc: Any = ..., scale: Any = ..., size: Any = ...
    ) -> ndarray: ...
    @staticmethod
    def uniform(
        low: Any = ..., high: Any = ..., size: Any = ...
    ) -> ndarray: ...
    @staticmethod
    def default_rng(seed: Any = ...) -> Any: ...

class maximum:
    def __call__(self, x1: Any, x2: Any) -> ndarray: ...
    @staticmethod
    def accumulate(a: Any, axis: Any = ...) -> ndarray: ...
